version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./etc/Dockerfile
      args:
        - ENV=local
    image: am_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8080:8080"
    command: /bin/sh -c "python manage.py collectstatic --noinput && python manage.py migrate && python manage.py runserver_plus 0.0.0.0:8080"

  postgres:
    image: postgres:11-alpine
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5437:5432"
