# Generated by Django 4.0.3 on 2022-12-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_tag_alter_comment_author_blog_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='body',
        ),
        migrations.AddField(
            model_name='blog',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default="2022-12-07 12:07"),
            preserve_default=False,
        ),
    ]
